# Generated by Django 2.2 on 2022-11-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifypro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifypro',
            old_name='slug',
            new_name='classification_slug',
        ),
    ]
