# Generated by Django 2.2 on 2022-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eircode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
