# Generated by Django 2.2 on 2022-12-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20221207_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket_item',
            old_name='product',
            new_name='products',
        ),
    ]
