# Generated by Django 2.2 on 2022-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20221207_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket_item',
            old_name='products',
            new_name='product',
        ),
    ]
