# Generated by Django 2.2 on 2022-11-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifypro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200, unique=True)),
                ('Product_price', models.FloatField()),
                ('Product_discription', models.TextField(blank=True, max_length=200)),
                ('Product_stock', models.IntegerField()),
                ('Product_isavailable', models.BooleanField(default=True)),
                ('Product_creation', models.DateTimeField(auto_now_add=True)),
                ('Product_modification', models.DateTimeField(auto_now=True)),
                ('Product_slug', models.SlugField(max_length=200, unique=True)),
                ('Product_img', models.ImageField(upload_to='media/product_photos')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifypro.Classifypro')),
            ],
        ),
    ]
